networks:
  autograder:

services:
  db:
    image: mysql:9.0.1
    profiles:
      - with-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - autograder

  app:
    image: ghcr.io/softwareconstruction240/autograder:latest
    ports:
      - "8080:8080"
    command: ["java", "-Dlog4j2.configurationFile=log4j.properties", "-Dlog4j2.debug=false", "-jar", "/app/target/automatico-1.0-SNAPSHOT.jar",
        "--db-host", "changeme",
        "--db-port", "changeme",
        "--db-name", "changeme",
        "--db-user", "changeme",
        "--db-pass", "changeme",
        "--frontend-url", "changeme",
        "--cas-callback-url", "changeme",
        "--canvas-token", "changeme",
        "--use-canvas", "true",
#        "--disable-compilation", # Enable me, if desired!
    ]
    networks:
      - autograder

  loki:
    image: grafana/loki:2.9.10
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - autograder

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    networks:
      - autograder

  watchtower:
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: containrrr/watchtower

volumes:
    db-data:
