version: '3.9'

services:
  db:
    image: mysql:latest
    profiles:
      - with-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    command: ["java", "-Dlog4j2.configurationFile=log4j.properties", "-Dlog4j2.debug=false", "-jar", "/app/target/automatico-1.0-SNAPSHOT.jar",
        "--db-url", "changeme",
        "--db-name", "changeme",
        "--db-user", "changeme",
        "--db-pass", "changeme",
        "--frontend-url", "changeme",
        "--cas-callback-url", "changeme",
        "--canvas-token", "changeme",
    ]


volumes:
    db-data:
