version: '3.9'

services:
  db:
    image: mysql:latest
    profiles:
      - with-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
    db-data:
