version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
    db-data: