name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies and build frontend
        run: |
          cd src/main/resources/frontend
          yarn
          yarn build

      - name: Build Java app
        run: mvn package

      - name: Transfer files to EC2 instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: target/automatico-1.0-SNAPSHOT.jar
          target: ${{ vars.EC2_TARGET_DIR }}/autograder.jar
