name: Docker Hub Deployment

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: "Docker Hub Deployment"
    runs-on: ubuntu-latest
    environment: production
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3   
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pawlh/cs240-autograder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
        
