name: Maven Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  maven-tests:
    name: "Run tests with Maven"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Test with Maven
        run: mvn test

  vue-type-check:
    name: "Run type checks with Vue"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Vue dependencies
        uses: actions/cache@v4
        with:
          path: |
            src/main/resources/frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install Deps
        run: yarn --cwd src/main/resources/frontend

      - name: Run Type Checks
        run: yarn --cwd src/main/resources/frontend run type-check
